[FILTER]
    Name        parser
    Match       kube.audit
    Key_Name    log
    Parser      json
    Reserve_Data On

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude user.groups system:serviceaccounts

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude user.username system:

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude verb list

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude verb watch

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude verb get

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude objectRef.resource events

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude objectRef.resource leases

[FILTER]
    Name    grep
    Match   kube.audit
    Exclude objectRef.resource apis
