groups:
- name: infrastructure-alerts
  rules:

  - alert: NodeDown
    expr: up == 0
    for: 2m
    labels:
      severity: critical
    annotations:
      summary: "Node down"
      description: "A node is not responding to Prometheus."

  - alert: HighCPUUsage
    expr: 100 - (avg by(instance) (rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High CPU usage"
      description: "CPU usage above 80%."

  - alert: HighMemoryUsage
    expr: (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes) < 0.15
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "High memory usage"
      description: "Memory usage above 85%."
